### ISSUE TITLE
compile ok but runs with error with "C7006: no work group size specified" 

### ISSUE THREAD

**Issue by zhangfq-chemistry** [florianblume/qt3d-gizmo#3]

**Comment by zhangfq-chemistry** [comment]
*** Problematic Fragment shader source code ***
#version 130
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#define lowp
#define mediump
#define highp
#line 1

uniform vec3 color;

void main(void) {
    gl_FragColor = vec4(color, 1.0);
}

***
QOpenGLShader::link: Compute info
------------
(0) : error C7006: no work group size specified

QOpenGLShader::link: Compute info
------------
(0) : error C7006: no work group size specified

**Comment by florianblume** [comment]
Hey @zhangfq-chemistry 

unfortunatley I never finished the project... The problem is that you need to draw the gizmo over all other objects and to successfully pick the gizmo you need to set the picking mode to all picks. But this way, you can pick parts of the gizmo which are covered by other parts of the gizmo. Since you cannot easily recover the camera matrix of the current ray in Qt3D I needed to transfer all computations to the shaders which doesn't work yet.

**Comment by florianblume** [comment]
I actually finished the implementation now! It doesn't use the compute shaders anymore but exploits that you can have prioritized picking in Qt3D. Try it out :)
